feat: Add timestampvm-rs as tempate
ava-labs/timestampvm-rs-template pull request #1
Opened 2023-11-13 17:42 UTC by dimitrovmaksim

Converts the timestampvm-rs code into a `cargo generate` template.

We probably need to add some placeholders to the various scripts, readme and also update the github workflows

2023-11-13 20:24 UTC, richardpringle approved these changes

2023-11-14 20:01 UTC, richardpringle requested changes
Just need to delete a couple of files then this is good to go

2023-11-14 20:01 UTC, richardpringle commented on .github/workflows/test-and-release.yml
Can we remove this file from the template? Testing here will be a little different than normal

2023-11-14 20:01 UTC, richardpringle commented on .rustfmt.nightly.toml
Can we remove this file? It was related to CI

2023-11-14 20:01 UTC, richardpringle commented on README.md
Can we update the readme to accurately describe how to use `cargo generate` (including how to install `cargo generate`)? Then we can point to a permalink to `timestampvm-rs`.

2023-11-14 20:01 UTC, richardpringle commented on cargo-generate.toml
👍

2023-11-14 20:01 UTC, richardpringle commented on deleteme
nice haha, thank you!

2023-11-14 20:01 UTC, richardpringle commented on scripts/tests.lint.sh
Can delete this file

2023-11-14 20:01 UTC, richardpringle commented on scripts/tests.unit.sh
Can delete this as well, people should know how to use `cargo test`

2023-11-14 20:01 UTC, richardpringle commented on scripts/tests.unused.sh
Can delete this as well

2023-11-15 09:21 UTC, dimitrovmaksim commented
```
PROTOC_VERSION=$(protoc --version | cut -f2 -d' ')
if [[ "${PROTOC_VERSION}" == "" ]] || [[ "${PROTOC_VERSION}" < 3.15.0 ]]; then
  echo "protoc must be installed and the version must be greater than 3.15.0"
  exit 255
fi
```

This condition is not working for me
```
$ protoc --version
libprotoc 25.0
```

But still the ```[[ "${PROTOC_VERSION}" < 3.15.0 ]]``` conditions results to false for me

2023-11-15 09:24 UTC, dimitrovmaksim commented on README.md
Updated the readme, but left the build and e2e test steps and added links to the timestampvm-rs repo

2023-11-15 16:39 UTC, richardpringle approved these changes
🥇

2023-11-15 16:39 UTC, merged